version: '3.8'

services:
  model-server:
    image: openvino/model_server:latest-gpu
    container_name: openvino-model-server
    volumes:
      - ./models:/models
    ports:
      - '8000:8000'  # REST API port
      - '9000:9000'  # gRPC port
    command: [
      "--port",
      "9000",
      "--rest_port",
      "8000",
      "--model_name",
      "catdog",
      "--model_path",
      "/models/catdog"
    ]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - model-server

  vite-client:
    build:
      context: ./vite-client
      dockerfile: Dockerfile
    container_name: vite-client
    ports:
      - "3000:80"
    depends_on:
      - backend
